### ISSUE TITLE
Compatibility with FoxGame / SuperOgame addons

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ogamespec/ogame-opensource#47]
Check the HTML code of the game for compatibility with major popular addons and custom scripts like InfoCompte.

- [x] FoxGame 1.5.1
- [x] SuperOGame 1.7.0
- [x] InfoCompte

**Comment by ogamespec** [comment]
SuperOGame is quite good, but for some reason it doesn't display the time in the event list. Everything else seems to be working.
Well, at least it is alive.
![image](https://github.com/ogamespec/ogame-opensource/assets/5828819/db49bced-af1d-4a19-9c34-f8b5da16f8c3)

**Comment by ogamespec** [comment]
FoxGame is installed in Firefox 7.0, but setting URLs other than official ones is not provided, you need to finalize the extension.

![image](https://github.com/ogamespec/ogame-opensource/assets/5828819/98f0db27-59ae-4e1c-89b1-6680022318b1)

**Comment by ogamespec** [comment]
InfoCompte seems to work, but the Google Charts API doesn't work, so no picture of the pie.

![image](https://github.com/ogamespec/ogame-opensource/assets/5828819/aad4fe13-f290-4760-8796-6ee5ea93eded)

**Comment by ogamespec** [comment]
Bottom line: The main addons are compatible, but require some tweaks:
- Manually specify the retroserver address instead of predefined by the GF server
- Manual language selection (since our retroserver is multi-language)
- Fix obsolete functionality, e.g. non-working Google Chart API
- Specifically FoxGame would be difficult to port as a modern extension, as it uses XUL there

All these tweaks will be done when the mood strikes, in other issues.
